import { configDigest, type PublishedConfig } from './publication.js';

export const CONFIG_PAYLOAD_SCHEMA_VERSION = 1;
export type PublicationOutcome = 'ack'|'nack';
export type PublicationPhase = 'empty'|'active'|'pending';
export type TransitionKind = 'published'|'activated'|'acknowledged'|'rejected'|'timed_out'|'rolled_back';
export interface PublicationRollout { targetNodes?:string[]; quorum?:number; timeoutMs:number }
export interface PublicationRecord<T=unknown> extends PublishedConfig<T>{payloadSchemaVersion:number;rollout?:PublicationRollout;sourceRevision?:number}
export interface PublicationAck{scope:string;revision:number;nodeId:string;digest:string;outcome:PublicationOutcome;detail?:string;recordedAt:number}
export interface PublicationTransition{id:number;scope:string;revision:number;kind:TransitionKind;actor:string;at:number;detail?:string}
export interface PublicationState{scope:string;stateVersion:number;phase:PublicationPhase;desiredRevision?:number;pendingRevision?:number;activeRevision?:number;previousActiveRevision?:number;deadlineAt?:number}
export interface PublicationSnapshot<T=unknown>{state:PublicationState;desired?:PublicationRecord<T>;pending?:PublicationRecord<T>;active?:PublicationRecord<T>;previous?:PublicationRecord<T>;acknowledgements:PublicationAck[]}
export type PublicationMutation<T=unknown>={ok:true;snapshot:PublicationSnapshot<T>;changed:boolean}|{ok:false;conflict:PublicationSnapshot<T>};
export interface ProposeInput<T>{scope:string;expectedRevision:number;expectedStateVersion?:number;payload:T;payloadSchemaVersion:number;digest:string;actor:string;now:number;rollout?:PublicationRollout}
export interface AckInput{scope:string;revision:number;nodeId:string;digest:string;outcome:PublicationOutcome;detail?:string;actor:string;now:number}
export interface RollbackInput{scope:string;expectedStateVersion:number;actor:string;now:number;toRevision?:number;reason?:string}
export interface PublicationStateStore{init():Promise<void>;snapshot<T=unknown>(scope:string):Promise<PublicationSnapshot<T>>;history<T=unknown>(scope:string,limit?:number):Promise<PublicationRecord<T>[]>;transitions(scope:string,limit?:number):Promise<PublicationTransition[]>;propose<T>(input:ProposeInput<T>):Promise<PublicationMutation<T>>;acknowledge(input:AckInput):Promise<PublicationMutation>;expire(scope:string,now:number,actor:string):Promise<PublicationMutation>;rollback(input:RollbackInput):Promise<PublicationMutation>}
interface MemoryScope{state:PublicationState;records:Map<number,PublicationRecord>;acks:Map<string,PublicationAck>;transitions:PublicationTransition[]}
const clone=<T>(v:T):T=>structuredClone(v);
function validScope(v:string){const s=v.trim()||'global';if(!/^[A-Za-z0-9._:-]{1,64}$/.test(s))throw new Error('invalid publication scope');return s}
function validNode(v:string){const s=v.trim();if(!/^[A-Za-z0-9._:-]{1,191}$/.test(s))throw new Error('invalid nodeId');return s}
export function assertSupportedPayloadSchema(v:number){if(!Number.isSafeInteger(v)||v<1)throw new Error('payloadSchemaVersion must be positive');if(v>CONFIG_PAYLOAD_SCHEMA_VERSION)throw new Error(`unsupported future config payload schema version: ${v}`)}
function rollout(v?:PublicationRollout){if(!v)return undefined;if(!Number.isSafeInteger(v.timeoutMs)||v.timeoutMs<1)throw new Error('timeoutMs must be positive');const targets=v.targetNodes?[...new Set(v.targetNodes.map(validNode))].sort():undefined;const ht=Boolean(targets?.length),hq=v.quorum!==undefined;if(ht===hq)throw new Error('rollout requires exactly one of targetNodes or quorum');if(hq&&(!Number.isSafeInteger(v.quorum)||v.quorum!<1))throw new Error('quorum must be positive');return{timeoutMs:v.timeoutMs,...(ht?{targetNodes:targets}:{quorum:v.quorum})}}
function snap<T>(s:MemoryScope):PublicationSnapshot<T>{const get=(r?:number)=>r===undefined?undefined:clone(s.records.get(r)) as PublicationRecord<T>|undefined;return{state:clone(s.state),desired:get(s.state.desiredRevision),pending:get(s.state.pendingRevision),active:get(s.state.activeRevision),previous:get(s.state.previousActiveRevision),acknowledgements:[...s.acks.values()].filter(a=>a.revision===s.state.pendingRevision).sort((a,b)=>a.nodeId.localeCompare(b.nodeId)).map(clone)}}
function satisfied(r:PublicationRecord,acks:PublicationAck[]){const ok=new Set(acks.filter(a=>a.outcome==='ack').map(a=>a.nodeId));return r.rollout?.targetNodes?r.rollout.targetNodes.every(n=>ok.has(n)):ok.size>=(r.rollout?.quorum??0)}
export class InMemoryPublicationStateStore implements PublicationStateStore{
 readonly #scopes=new Map<string,MemoryScope>();#tail=Promise.resolve();#tid=0;async init(){}
 async #lock<T>(f:()=>T|Promise<T>){const p=this.#tail;let release!:()=>void;this.#tail=new Promise<void>(r=>release=r);await p;try{return await f()}finally{release()}}
 #scope(name:string){const key=validScope(name);let s=this.#scopes.get(key);if(!s){s={state:{scope:key,stateVersion:0,phase:'empty'},records:new Map(),acks:new Map(),transitions:[]};this.#scopes.set(key,s)}return s}
 #event(s:MemoryScope,revision:number,kind:TransitionKind,actor:string,at:number,detail?:string){s.transitions.push({id:++this.#tid,scope:s.state.scope,revision,kind,actor,at,detail})}
 async snapshot<T>(scope:string){return this.#lock(()=>snap<T>(this.#scope(scope)))}
 async history<T>(scope:string,limit=100){return this.#lock(()=>[...this.#scope(scope).records.values()].sort((a,b)=>b.revision-a.revision).slice(0,Math.max(0,limit)).map(clone) as PublicationRecord<T>[])}
 async transitions(scope:string,limit=100){return this.#lock(()=>this.#scope(scope).transitions.slice(-Math.max(0,limit)).reverse().map(clone))}
 async propose<T>(i:ProposeInput<T>):Promise<PublicationMutation<T>>{return this.#lock(()=>{const s=this.#scope(i.scope);assertSupportedPayloadSchema(i.payloadSchemaVersion);const ro=rollout(i.rollout);if(i.expectedRevision!==(s.state.desiredRevision??0)||(i.expectedStateVersion!==undefined&&i.expectedStateVersion!==s.state.stateVersion)||s.state.pendingRevision!==undefined)return{ok:false,conflict:snap<T>(s)};const rev=Math.max(0,...s.records.keys())+1;const record:PublicationRecord<T>={scope:s.state.scope,revision:rev,digest:i.digest,payload:clone(i.payload),publishedAt:i.now,publishedBy:i.actor,payloadSchemaVersion:i.payloadSchemaVersion,rollout:ro};s.records.set(rev,record);s.state.stateVersion++;s.state.desiredRevision=rev;this.#event(s,rev,'published',i.actor,i.now);s.state.previousActiveRevision=s.state.activeRevision;if(ro){s.state.pendingRevision=rev;s.state.deadlineAt=i.now+ro.timeoutMs;s.state.phase='pending'}else{s.state.activeRevision=rev;s.state.phase='active';this.#event(s,rev,'activated',i.actor,i.now,'legacy immediate activation')}return{ok:true,snapshot:snap<T>(s),changed:true}})}
 #rollbackPending(s:MemoryScope,actor:string,now:number,kind:'timed_out'|'rolled_back',detail:string,bump=true){const failed=s.state.pendingRevision;if(failed===undefined)return;s.state.desiredRevision=s.state.activeRevision;s.state.pendingRevision=undefined;s.state.deadlineAt=undefined;s.state.phase=s.state.activeRevision===undefined?'empty':'active';if(bump)s.state.stateVersion++;this.#event(s,failed,kind,actor,now,detail)}
 async acknowledge(i:AckInput):Promise<PublicationMutation>{return this.#lock(()=>{const s=this.#scope(i.scope),node=validNode(i.nodeId),pending=s.state.pendingRevision===undefined?undefined:s.records.get(s.state.pendingRevision);if(!pending||pending.revision!==i.revision)return{ok:false,conflict:snap(s)};if(pending.digest!==i.digest)throw new Error('acknowledgement digest mismatch');if(s.state.deadlineAt!==undefined&&i.now>=s.state.deadlineAt){this.#rollbackPending(s,i.actor,i.now,'timed_out','ack arrived after deadline');return{ok:true,snapshot:snap(s),changed:true}}if(pending.rollout?.targetNodes&&!pending.rollout.targetNodes.includes(node))throw new Error('node is not a rollout target');const key=`${i.revision}:${node}`,old=s.acks.get(key);if(old){if(old.digest===i.digest&&old.outcome===i.outcome&&old.detail===i.detail)return{ok:true,snapshot:snap(s),changed:false};throw new Error('node acknowledgement conflict')}s.acks.set(key,{scope:s.state.scope,revision:i.revision,nodeId:node,digest:i.digest,outcome:i.outcome,detail:i.detail,recordedAt:i.now});s.state.stateVersion++;this.#event(s,i.revision,i.outcome==='ack'?'acknowledged':'rejected',i.actor,i.now,i.detail??node);if(i.outcome==='nack')this.#rollbackPending(s,i.actor,i.now,'rolled_back',`NACK from ${node}`,false);else if(satisfied(pending,[...s.acks.values()].filter(a=>a.revision===pending.revision))){s.state.activeRevision=pending.revision;s.state.pendingRevision=undefined;s.state.deadlineAt=undefined;s.state.phase='active';this.#event(s,pending.revision,'activated',i.actor,i.now)}return{ok:true,snapshot:snap(s),changed:true}})}
 async expire(scope:string,now:number,actor='system'):Promise<PublicationMutation>{return this.#lock(()=>{const s=this.#scope(scope);if(s.state.pendingRevision===undefined||s.state.deadlineAt===undefined||now<s.state.deadlineAt)return{ok:true,snapshot:snap(s),changed:false};this.#rollbackPending(s,actor,now,'timed_out','rollout deadline exceeded');return{ok:true,snapshot:snap(s),changed:true}})}
 async rollback(i:RollbackInput):Promise<PublicationMutation>{return this.#lock(()=>{const s=this.#scope(i.scope);if(s.state.stateVersion!==i.expectedStateVersion)return{ok:false,conflict:snap(s)};const targetRev=i.toRevision??s.state.previousActiveRevision,target=targetRev===undefined?undefined:s.records.get(targetRev);if(!target)throw new Error('rollback target revision not found');assertSupportedPayloadSchema(target.payloadSchemaVersion);const rev=Math.max(0,...s.records.keys())+1,record:PublicationRecord={...clone(target),revision:rev,publishedAt:i.now,publishedBy:i.actor,sourceRevision:target.revision,rollout:undefined};s.records.set(rev,record);s.state.previousActiveRevision=s.state.activeRevision;s.state.activeRevision=rev;s.state.desiredRevision=rev;s.state.pendingRevision=undefined;s.state.deadlineAt=undefined;s.state.phase='active';s.state.stateVersion++;this.#event(s,rev,'rolled_back',i.actor,i.now,i.reason??`restored revision ${target.revision}`);this.#event(s,rev,'activated',i.actor,i.now,'manual rollback');return{ok:true,snapshot:snap(s),changed:true}})}
}
export class ConfigPublicationStateMachine{
 constructor(readonly store:PublicationStateStore,readonly now:()=>number=Date.now){}init(){return this.store.init()}get<T=unknown>(scope='global'){return this.store.snapshot<T>(validScope(scope))}history<T=unknown>(scope='global',limit=100){return this.store.history<T>(validScope(scope),limit)}transitions(scope='global',limit=100){return this.store.transitions(validScope(scope),limit)}
 publish<T>(i:{scope?:string;expectedRevision:number;expectedStateVersion?:number;payload:T;payloadSchemaVersion?:number;actor:string;rollout?:PublicationRollout}){const version=i.payloadSchemaVersion??1;assertSupportedPayloadSchema(version);return this.store.propose({scope:validScope(i.scope??'global'),expectedRevision:i.expectedRevision,expectedStateVersion:i.expectedStateVersion,payload:i.payload,payloadSchemaVersion:version,digest:configDigest(i.payload),actor:i.actor,now:this.now(),rollout:rollout(i.rollout)})}
 acknowledge(i:Omit<AckInput,'now'>){return this.store.acknowledge({...i,scope:validScope(i.scope),now:this.now()})}reconcile(scope='global',actor='system'){return this.store.expire(validScope(scope),this.now(),actor)}rollback(i:Omit<RollbackInput,'now'>){return this.store.rollback({...i,scope:validScope(i.scope),now:this.now()})}
}
