import{assertSupportedPayloadSchema}from'./publication-state.js';import type{AckInput,PublicationAck,PublicationMutation,PublicationRecord,PublicationSnapshot,PublicationState,PublicationStateStore,PublicationTransition,ProposeInput,RollbackInput}from'./publication-state.js';
export interface MySqlPublicationConnection{execute(sql:string,params?:readonly unknown[]):Promise<unknown>;beginTransaction():Promise<void>;commit():Promise<void>;rollback():Promise<void>;release():void}
export interface MySqlPublicationPool{execute(sql:string,params?:readonly unknown[]):Promise<unknown>;getConnection():Promise<MySqlPublicationConnection>}
const identifier=(v:string)=>{if(!/^[A-Za-z0-9_]+$/.test(v))throw new Error('invalid MySQL publication table prefix');return v};
const rows=(r:unknown):Record<string,unknown>[]=>Array.isArray(r)&&Array.isArray(r[0])?r[0] as Record<string,unknown>[]:[];
const affected=(r:unknown)=>{const x=Array.isArray(r)?r[0]:r,a=(x as{affectedRows?:unknown})?.affectedRows;return typeof a==='number'?a:0};
const json=(v:unknown)=>JSON.stringify(v);
const parse=<T>(v:unknown):T=>typeof v==='string'?JSON.parse(v) as T:v as T;
const optional=(v:unknown)=>v===null||v===undefined?undefined:Number(v);
export class MySqlPublicationStateStore implements PublicationStateStore{
 readonly #pool:MySqlPublicationPool;readonly #state:string;readonly #history:string;readonly #acks:string;readonly #events:string;
 constructor(pool:MySqlPublicationPool,prefix='mohobot_config_publication'){const p=identifier(prefix);this.#pool=pool;this.#state=`${p}_state`;this.#history=`${p}_history`;this.#acks=`${p}_acks`;this.#events=`${p}_events`}
 async init(){
  await this.#pool.execute(`CREATE TABLE IF NOT EXISTS ${this.#history} (scope VARCHAR(64) NOT NULL, revision BIGINT UNSIGNED NOT NULL, digest CHAR(64) NOT NULL, payload_schema_version INT UNSIGNED NOT NULL, payload_json JSON NOT NULL, rollout_json JSON NULL, source_revision BIGINT UNSIGNED NULL, published_at BIGINT NOT NULL, published_by VARCHAR(191) NOT NULL, PRIMARY KEY(scope,revision), UNIQUE KEY uq_scope_digest_revision(scope,digest,revision))`);
  await this.#pool.execute(`CREATE TABLE IF NOT EXISTS ${this.#state} (scope VARCHAR(64) PRIMARY KEY, state_version BIGINT UNSIGNED NOT NULL, phase VARCHAR(16) NOT NULL, desired_revision BIGINT UNSIGNED NULL, pending_revision BIGINT UNSIGNED NULL, active_revision BIGINT UNSIGNED NULL, previous_active_revision BIGINT UNSIGNED NULL, deadline_at BIGINT NULL, updated_at BIGINT NOT NULL)`);
  await this.#pool.execute(`CREATE TABLE IF NOT EXISTS ${this.#acks} (scope VARCHAR(64) NOT NULL, revision BIGINT UNSIGNED NOT NULL, node_id VARCHAR(191) NOT NULL, digest CHAR(64) NOT NULL, outcome VARCHAR(8) NOT NULL, detail VARCHAR(512) NULL, recorded_at BIGINT NOT NULL, PRIMARY KEY(scope,revision,node_id))`);
  await this.#pool.execute(`CREATE TABLE IF NOT EXISTS ${this.#events} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, scope VARCHAR(64) NOT NULL, revision BIGINT UNSIGNED NOT NULL, kind VARCHAR(32) NOT NULL, actor VARCHAR(191) NOT NULL, occurred_at BIGINT NOT NULL, detail VARCHAR(512) NULL, KEY idx_scope_id(scope,id))`);
 }
 #record<T>(r:Record<string,unknown>):PublicationRecord<T>{return{scope:String(r.scope),revision:Number(r.revision),digest:String(r.digest),payload:parse<T>(r.payload_json),payloadSchemaVersion:Number(r.payload_schema_version),rollout:r.rollout_json===null||r.rollout_json===undefined?undefined:parse(r.rollout_json),sourceRevision:optional(r.source_revision),publishedAt:Number(r.published_at),publishedBy:String(r.published_by)}}
 #stateRow(r:Record<string,unknown>):PublicationState{return{scope:String(r.scope),stateVersion:Number(r.state_version),phase:String(r.phase) as PublicationState['phase'],desiredRevision:optional(r.desired_revision),pendingRevision:optional(r.pending_revision),activeRevision:optional(r.active_revision),previousActiveRevision:optional(r.previous_active_revision),deadlineAt:optional(r.deadline_at)}}
 async #snapshotWith(c:{execute(sql:string,params?:readonly unknown[]):Promise<unknown>},scope:string,lock=false):Promise<PublicationSnapshot>{const sr=rows(await c.execute(`SELECT * FROM ${this.#state} WHERE scope=?${lock?' FOR UPDATE':''}`,[scope]))[0],state=sr?this.#stateRow(sr):{scope,stateVersion:0,phase:'empty' as const};const revisions=[state.desiredRevision,state.pendingRevision,state.activeRevision,state.previousActiveRevision].filter((v):v is number=>v!==undefined);const records=new Map<number,PublicationRecord>();if(revisions.length){const rr=rows(await c.execute(`SELECT * FROM ${this.#history} WHERE scope=? AND revision IN (${revisions.map(()=>'?').join(',')})`,[scope,...revisions]));for(const r of rr)records.set(Number(r.revision),this.#record(r))}const ar=state.pendingRevision===undefined?[]:rows(await c.execute(`SELECT * FROM ${this.#acks} WHERE scope=? AND revision=? ORDER BY node_id`,[scope,state.pendingRevision]));return{state,desired:records.get(state.desiredRevision??-1),pending:records.get(state.pendingRevision??-1),active:records.get(state.activeRevision??-1),previous:records.get(state.previousActiveRevision??-1),acknowledgements:ar.map(r=>({scope:String(r.scope),revision:Number(r.revision),nodeId:String(r.node_id),digest:String(r.digest),outcome:String(r.outcome) as PublicationAck['outcome'],detail:r.detail==null?undefined:String(r.detail),recordedAt:Number(r.recorded_at)}))}}
 snapshot<T>(scope:string){return this.#snapshotWith(this.#pool,scope) as Promise<PublicationSnapshot<T>>}
 async history<T>(scope:string,limit=100){return rows(await this.#pool.execute(`SELECT * FROM ${this.#history} WHERE scope=? ORDER BY revision DESC LIMIT ?`,[scope,Math.max(0,limit)])).map(r=>this.#record<T>(r))}
 async transitions(scope:string,limit=100){return rows(await this.#pool.execute(`SELECT * FROM ${this.#events} WHERE scope=? ORDER BY id DESC LIMIT ?`,[scope,Math.max(0,limit)])).map(r=>({id:Number(r.id),scope:String(r.scope),revision:Number(r.revision),kind:String(r.kind),actor:String(r.actor),at:Number(r.occurred_at),detail:r.detail==null?undefined:String(r.detail)}) as PublicationTransition)}
 async #tx<T>(f:(c:MySqlPublicationConnection)=>Promise<T>){const c=await this.#pool.getConnection();try{await c.beginTransaction();const out=await f(c);await c.commit();return out}catch(error){try{await c.rollback()}catch(rollbackError){throw new AggregateError([error,rollbackError],'publication transaction and rollback failed')}throw error}finally{c.release()}}
 async #event(c:MySqlPublicationConnection,scope:string,rev:number,kind:string,actor:string,at:number,detail?:string){await c.execute(`INSERT INTO ${this.#events} (scope,revision,kind,actor,occurred_at,detail) VALUES (?,?,?,?,?,?)`,[scope,rev,kind,actor,at,detail??null])}
 async propose<T>(i:ProposeInput<T>):Promise<PublicationMutation<T>>{assertSupportedPayloadSchema(i.payloadSchemaVersion);return this.#tx(async c=>{await c.execute(`INSERT INTO ${this.#state} (scope,state_version,phase,updated_at) VALUES (?,0,'empty',?) ON DUPLICATE KEY UPDATE scope=VALUES(scope)`,[i.scope,i.now]);const current=await this.#snapshotWith(c,i.scope,true);if(i.expectedRevision!==(current.state.desiredRevision??0)||(i.expectedStateVersion!==undefined&&i.expectedStateVersion!==current.state.stateVersion)||current.state.pendingRevision!==undefined)return{ok:false,conflict:current as PublicationSnapshot<T>};const maxRow=rows(await c.execute(`SELECT COALESCE(MAX(revision),0) AS max_revision FROM ${this.#history} WHERE scope=? FOR UPDATE`,[i.scope]))[0];const rev=Number(maxRow?.max_revision??0)+1;await c.execute(`INSERT INTO ${this.#history} (scope,revision,digest,payload_schema_version,payload_json,rollout_json,source_revision,published_at,published_by) VALUES (?,?,?,?,CAST(? AS JSON),CAST(? AS JSON),NULL,?,?)`,[i.scope,rev,i.digest,i.payloadSchemaVersion,json(i.payload),i.rollout?json(i.rollout):null,i.now,i.actor]);const active=i.rollout?current.state.activeRevision:rev,pending=i.rollout?rev:null,deadline=i.rollout?i.now+i.rollout.timeoutMs:null,phase=i.rollout?'pending':'active';const u=await c.execute(`UPDATE ${this.#state} SET state_version=state_version+1,phase=?,desired_revision=?,pending_revision=?,active_revision=?,previous_active_revision=?,deadline_at=?,updated_at=? WHERE scope=? AND state_version=?`,[phase,rev,pending,active,current.state.activeRevision??null,deadline,i.now,i.scope,current.state.stateVersion]);if(affected(u)!==1)throw new Error('publication state changed during locked proposal');await this.#event(c,i.scope,rev,'published',i.actor,i.now);if(!i.rollout)await this.#event(c,i.scope,rev,'activated',i.actor,i.now,'legacy immediate activation');return{ok:true,snapshot:await this.#snapshotWith(c,i.scope) as PublicationSnapshot<T>,changed:true}})}
 async acknowledge(i:AckInput):Promise<PublicationMutation>{return this.#tx(async c=>{const current=await this.#snapshotWith(c,i.scope,true),pending=current.pending;if(!pending||pending.revision!==i.revision)return{ok:false,conflict:current};if(pending.digest!==i.digest)throw new Error('acknowledgement digest mismatch');if(pending.rollout?.targetNodes&&!pending.rollout.targetNodes.includes(i.nodeId))throw new Error('node is not a rollout target');if(current.state.deadlineAt!==undefined&&i.now>=current.state.deadlineAt)return this.#rollbackPending(c,current,i.actor,i.now,'timed_out','ack arrived after deadline');const old=rows(await c.execute(`SELECT * FROM ${this.#acks} WHERE scope=? AND revision=? AND node_id=? FOR UPDATE`,[i.scope,i.revision,i.nodeId]))[0];if(old){if(String(old.digest)===i.digest&&String(old.outcome)===i.outcome&&(old.detail==null?undefined:String(old.detail))===i.detail)return{ok:true,snapshot:current,changed:false};throw new Error('node acknowledgement conflict')}await c.execute(`INSERT INTO ${this.#acks} (scope,revision,node_id,digest,outcome,detail,recorded_at) VALUES (?,?,?,?,?,?,?)`,[i.scope,i.revision,i.nodeId,i.digest,i.outcome,i.detail??null,i.now]);await this.#event(c,i.scope,i.revision,i.outcome==='ack'?'acknowledged':'rejected',i.actor,i.now,i.detail??i.nodeId);if(i.outcome==='nack')return this.#rollbackPending(c,await this.#snapshotWith(c,i.scope),i.actor,i.now,'rolled_back',`NACK from ${i.nodeId}`);const acks=rows(await c.execute(`SELECT node_id FROM ${this.#acks} WHERE scope=? AND revision=? AND outcome='ack'`,[i.scope,i.revision])).map(r=>String(r.node_id));const reached=pending.rollout?.targetNodes?pending.rollout.targetNodes.every(n=>acks.includes(n)):acks.length>=(pending.rollout?.quorum??0);if(reached){await c.execute(`UPDATE ${this.#state} SET state_version=state_version+1,phase='active',pending_revision=NULL,active_revision=?,deadline_at=NULL,updated_at=? WHERE scope=?`,[i.revision,i.now,i.scope]);await this.#event(c,i.scope,i.revision,'activated',i.actor,i.now)}else await c.execute(`UPDATE ${this.#state} SET state_version=state_version+1,updated_at=? WHERE scope=?`,[i.now,i.scope]);return{ok:true,snapshot:await this.#snapshotWith(c,i.scope),changed:true}})}
 async #rollbackPending(c:MySqlPublicationConnection,current:PublicationSnapshot,actor:string,now:number,kind:string,detail:string):Promise<PublicationMutation>{const failed=current.state.pendingRevision;if(failed===undefined)return{ok:true,snapshot:current,changed:false};await c.execute(`UPDATE ${this.#state} SET state_version=state_version+1,phase=?,desired_revision=active_revision,pending_revision=NULL,deadline_at=NULL,updated_at=? WHERE scope=?`,[current.state.activeRevision===undefined?'empty':'active',now,current.state.scope]);await this.#event(c,current.state.scope,failed,kind,actor,now,detail);return{ok:true,snapshot:await this.#snapshotWith(c,current.state.scope),changed:true}}
 async expire(scope:string,now:number,actor:string):Promise<PublicationMutation>{return this.#tx(async c=>{const current=await this.#snapshotWith(c,scope,true);if(current.state.pendingRevision===undefined||current.state.deadlineAt===undefined||now<current.state.deadlineAt)return{ok:true,snapshot:current,changed:false};return this.#rollbackPending(c,current,actor,now,'timed_out','rollout deadline exceeded')})}
 async rollback(i:RollbackInput):Promise<PublicationMutation>{return this.#tx(async c=>{const current=await this.#snapshotWith(c,i.scope,true);if(current.state.stateVersion!==i.expectedStateVersion)return{ok:false,conflict:current};const targetRev=i.toRevision??current.state.previousActiveRevision;if(targetRev===undefined)throw new Error('rollback target revision not found');const tr=rows(await c.execute(`SELECT * FROM ${this.#history} WHERE scope=? AND revision=?`,[i.scope,targetRev]))[0];if(!tr)throw new Error('rollback target revision not found');const target=this.#record(tr);if(target.payloadSchemaVersion>1)throw new Error(`unsupported future config payload schema version: ${target.payloadSchemaVersion}`);const max=rows(await c.execute(`SELECT COALESCE(MAX(revision),0) AS max_revision FROM ${this.#history} WHERE scope=? FOR UPDATE`,[i.scope]))[0],rev=Number(max?.max_revision??0)+1;await c.execute(`INSERT INTO ${this.#history} (scope,revision,digest,payload_schema_version,payload_json,rollout_json,source_revision,published_at,published_by) VALUES (?,?,?,?,CAST(? AS JSON),NULL,?,?,?)`,[i.scope,rev,target.digest,target.payloadSchemaVersion,json(target.payload),target.revision,i.now,i.actor]);await c.execute(`UPDATE ${this.#state} SET state_version=state_version+1,phase='active',desired_revision=?,pending_revision=NULL,active_revision=?,previous_active_revision=?,deadline_at=NULL,updated_at=? WHERE scope=?`,[rev,rev,current.state.activeRevision??null,i.now,i.scope]);await this.#event(c,i.scope,rev,'rolled_back',i.actor,i.now,i.reason??`restored revision ${target.revision}`);await this.#event(c,i.scope,rev,'activated',i.actor,i.now,'manual rollback');return{ok:true,snapshot:await this.#snapshotWith(c,i.scope),changed:true}})}
}
