import{describe,expect,it}from'vitest';import{ConfigPublicationStateMachine,InMemoryPublicationStateStore}from'./publication-state.js';
const principalTime=()=>{let now=100;return{now:()=>now,set:(v:number)=>now=v}};
describe('ConfigPublicationStateMachine',()=>{
 it('preserves legacy immediate activation and immutable history',async()=>{const m=new ConfigPublicationStateMachine(new InMemoryPublicationStateStore,()=>10);const r=await m.publish({expectedRevision:0,payload:{v:1},actor:'admin'});expect(r.ok&&r.snapshot.state.activeRevision).toBe(1);const history=await m.history();expect(history).toHaveLength(1);(history[0]!.payload as{v:number}).v=99;expect((await m.history<{v:number}>())[0]!.payload.v).toBe(1)});
 it('serializes concurrent publishers with one CAS winner',async()=>{const m=new ConfigPublicationStateMachine(new InMemoryPublicationStateStore,()=>10);const results=await Promise.all([m.publish({expectedRevision:0,payload:{v:'a'},actor:'a'}),m.publish({expectedRevision:0,payload:{v:'b'},actor:'b'})]);expect(results.filter(r=>r.ok)).toHaveLength(1);expect(results.filter(r=>!r.ok)).toHaveLength(1);expect(await m.history()).toHaveLength(1)});
 it('activates only after quorum distinct ACKs and makes ACK idempotent',async()=>{const t=principalTime(),m=new ConfigPublicationStateMachine(new InMemoryPublicationStateStore,t.now);const p=await m.publish({expectedRevision:0,payload:{v:1},actor:'a',rollout:{quorum:2,timeoutMs:100}});expect(p.ok).toBe(true);if(!p.ok)return;const digest=p.snapshot.pending!.digest;const one=await m.acknowledge({scope:'global',revision:1,nodeId:'n1',digest,outcome:'ack',actor:'n1'});expect(one.ok&&one.snapshot.state.phase).toBe('pending');const duplicate=await m.acknowledge({scope:'global',revision:1,nodeId:'n1',digest,outcome:'ack',actor:'n1'});expect(duplicate.ok&&duplicate.changed).toBe(false);const two=await m.acknowledge({scope:'global',revision:1,nodeId:'n2',digest,outcome:'ack',actor:'n2'});expect(two.ok&&two.snapshot.state.activeRevision).toBe(1)});
 it('requires every explicit target and rejects non-target ACK',async()=>{const m=new ConfigPublicationStateMachine(new InMemoryPublicationStateStore,()=>1);const p=await m.publish({expectedRevision:0,payload:{v:1},actor:'a',rollout:{targetNodes:['b','a','a'],timeoutMs:10}});if(!p.ok)return;await expect(m.acknowledge({scope:'global',revision:1,nodeId:'x',digest:p.snapshot.pending!.digest,outcome:'ack',actor:'x'})).rejects.toThrow('not a rollout target')});
 it('rolls NACK and timeout back to previous active',async()=>{const t=principalTime(),m=new ConfigPublicationStateMachine(new InMemoryPublicationStateStore,t.now);await m.publish({expectedRevision:0,payload:{v:1},actor:'a'});const p=await m.publish({expectedRevision:1,payload:{v:2},actor:'a',rollout:{quorum:2,timeoutMs:50}});if(!p.ok)return;const n=await m.acknowledge({scope:'global',revision:2,nodeId:'n1',digest:p.snapshot.pending!.digest,outcome:'nack',actor:'n1'});expect(n.ok&&n.snapshot.state.activeRevision).toBe(1);expect(n.ok&&n.snapshot.state.desiredRevision).toBe(1);const p2=await m.publish({expectedRevision:1,payload:{v:3},actor:'a',rollout:{quorum:1,timeoutMs:50}});expect(p2.ok&&p2.snapshot.pending?.revision).toBe(3);t.set(151);const expired=await m.reconcile();expect(expired.ok&&expired.changed).toBe(true);expect(expired.ok&&expired.snapshot.state.activeRevision).toBe(1)});
 it('manual rollback is CAS guarded and creates a new immutable revision',async()=>{const m=new ConfigPublicationStateMachine(new InMemoryPublicationStateStore,()=>10);await m.publish({expectedRevision:0,payload:{v:1},actor:'a'});await m.publish({expectedRevision:1,payload:{v:2},actor:'a'});const state=await m.get();const stale=await m.rollback({scope:'global',expectedStateVersion:state.state.stateVersion-1,actor:'a'});expect(stale.ok).toBe(false);const ok=await m.rollback({scope:'global',expectedStateVersion:state.state.stateVersion,actor:'a'});expect(ok.ok&&ok.snapshot.state.activeRevision).toBe(3);expect(ok.ok&&ok.snapshot.active?.sourceRevision).toBe(1);expect((await m.history()).map(x=>x.revision)).toEqual([3,2,1])});
 it('rejects future payload schemas before persistence and rollback activation',async()=>{const m=new ConfigPublicationStateMachine(new InMemoryPublicationStateStore,()=>1);expect(()=>m.publish({expectedRevision:0,payload:{},payloadSchemaVersion:2,actor:'a'})).toThrow('future');expect(await m.history()).toHaveLength(0)});
});
