import{createHash}from'node:crypto';
export interface PublishedConfig<T=unknown>{scope:string;revision:number;digest:string;payload:T;publishedAt:number;publishedBy:string;}
export type PublishResult<T=unknown>={ok:true;publication:PublishedConfig<T>}|{ok:false;conflict:PublishedConfig<T>|undefined};
export interface ConfigPublicationStore{get<T=unknown>(scope:string):Promise<PublishedConfig<T>|undefined>;compareAndSet<T=unknown>(input:{scope:string;expectedRevision:number;payload:T;digest:string;actor:string;now:number}):Promise<PublishResult<T>>;}
function canonical(value:unknown):string{if(value===null)return'null';if(typeof value==='string'||typeof value==='boolean')return JSON.stringify(value);if(typeof value==='number'){if(!Number.isFinite(value))throw new Error('config contains non-finite number');return String(value);}if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object'){const r=value as Record<string,unknown>;return`{${Object.keys(r).sort().map(k=>`${JSON.stringify(k)}:${canonical(r[k])}`).join(',')}}`;}throw new Error('config contains unsupported value');}
export function configDigest(payload:unknown):string{return createHash('sha256').update(canonical(payload)).digest('hex');}
export class ConfigPublicationService{readonly #store:ConfigPublicationStore;readonly #now:()=>number;constructor(store:ConfigPublicationStore,now:()=>number=Date.now){this.#store=store;this.#now=now;}get<T=unknown>(scope='global'){return this.#store.get<T>(scope);}async publish<T>(input:{scope?:string;expectedRevision:number;payload:T;actor:string}):Promise<PublishResult<T>>{if(!Number.isSafeInteger(input.expectedRevision)||input.expectedRevision<0)throw new Error('expectedRevision must be non-negative');const scope=input.scope?.trim()||'global';return this.#store.compareAndSet({scope,expectedRevision:input.expectedRevision,payload:input.payload,digest:configDigest(input.payload),actor:input.actor,now:this.#now()});}}
export interface MySqlCasClient{execute(sql:string,params?:readonly unknown[]):Promise<unknown>;}
function affected(result:unknown):number{const first=Array.isArray(result)?result[0]:result;return typeof(first as{affectedRows?:unknown})?.affectedRows==='number'?(first as{affectedRows:number}).affectedRows:0;}
export class MySqlConfigPublicationStore implements ConfigPublicationStore{readonly #client:MySqlCasClient;readonly #table:string;constructor(client:MySqlCasClient,table='mohobot_config_publications'){if(!/^[A-Za-z0-9_]+$/.test(table))throw new Error('invalid publication table');this.#client=client;this.#table=table;}async init(){await this.#client.execute(`CREATE TABLE IF NOT EXISTS ${this.#table} (scope VARCHAR(64) PRIMARY KEY, revision BIGINT UNSIGNED NOT NULL, digest CHAR(64) NOT NULL, payload_json JSON NOT NULL, published_at BIGINT NOT NULL, published_by VARCHAR(191) NOT NULL)`);}async get<T=unknown>(scope:string):Promise<PublishedConfig<T>|undefined>{const result=await this.#client.execute(`SELECT scope,revision,digest,payload_json,published_at,published_by FROM ${this.#table} WHERE scope=?`,[scope]);const rows=Array.isArray(result)&&Array.isArray(result[0])?result[0]as Array<Record<string,unknown>>:[];const row=rows[0];if(!row)return undefined;const payload=typeof row.payload_json==='string'?JSON.parse(row.payload_json):row.payload_json;return{scope:String(row.scope),revision:Number(row.revision),digest:String(row.digest),payload:payload as T,publishedAt:Number(row.published_at),publishedBy:String(row.published_by)};}async compareAndSet<T>(i:{scope:string;expectedRevision:number;payload:T;digest:string;actor:string;now:number}):Promise<PublishResult<T>>{const json=JSON.stringify(i.payload);if(i.expectedRevision===0){const r=await this.#client.execute(`INSERT INTO ${this.#table} (scope,revision,digest,payload_json,published_at,published_by) VALUES (?,1,?,CAST(? AS JSON),?,?) ON DUPLICATE KEY UPDATE scope=scope`,[i.scope,i.digest,json,i.now,i.actor]);if(affected(r)===1)return{ok:true,publication:{scope:i.scope,revision:1,digest:i.digest,payload:i.payload,publishedAt:i.now,publishedBy:i.actor}};}else{const r=await this.#client.execute(`UPDATE ${this.#table} SET revision=revision+1,digest=?,payload_json=CAST(? AS JSON),published_at=?,published_by=? WHERE scope=? AND revision=?`,[i.digest,json,i.now,i.actor,i.scope,i.expectedRevision]);if(affected(r)===1)return{ok:true,publication:{scope:i.scope,revision:i.expectedRevision+1,digest:i.digest,payload:i.payload,publishedAt:i.now,publishedBy:i.actor}};}return{ok:false,conflict:await this.get<T>(i.scope)};}}
