import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { fileURLToPath } from 'node:url';
import { SqliteStorage } from '../src/storage/sqlite.js';
import { createNullLogger } from '../src/core/logger.js';

export interface SetupOptions {
  rootDir?: string;
  nonInteractive?: boolean;
  force?: boolean;
  input?: NodeJS.ReadableStream;
  output?: NodeJS.WritableStream;
}

export interface SetupResult {
  rootDir: string;
  envFile: string;
  envCreated: boolean;
  adminToken: string;
  directoriesCreated: string[];
  sqlitePath: string;
  sqliteInitialized: boolean;
}

const DIRECTORIES = [
  'config/bots',
  'data/admin',
  'data/characters',
  'data/external-prompts',
  'data/memory',
  'data/models',
  'data/prompts',
  'data/runtime',
  'data/storage',
  'data/world',
  'logs',
  '.secrets',
] as const;

function token(): string {
  return `moho_${crypto.randomBytes(32).toString('base64url')}`;
}

async function exists(file: string): Promise<boolean> {
  try { await fs.access(file); return true; } catch { return false; }
}

function envContent(adminToken: string): string {
  return [
    '# Generated by npm run setup. Local-only; never commit this file.',
    `MOHO_ADMIN_TOKEN=${adminToken}`,
    'MOHO_ADAPTER=discord',
    'LOG_LEVEL=info',
    '# DISCORD_TOKEN=',
    '# AI_API_KEY=',
    '# AI_BASE_URL=https://integrate.api.nvidia.com/v1',
    '# AI_MODEL=',
    '# NVIDIA_API_KEY=',
    '# KILO_API_KEY=',
    '# MOHO_ADMIN_HOST=127.0.0.1',
    '# MOHO_ADMIN_PORT=3210',
    '',
  ].join('\n');
}

async function confirm(question: string, inputStream: NodeJS.ReadableStream, outputStream: NodeJS.WritableStream): Promise<boolean> {
  const rl = readline.createInterface({ input: inputStream as NodeJS.ReadableStream & AsyncIterable<string>, output: outputStream as NodeJS.WritableStream });
  try { return (await rl.question(`${question} [y/N] `)).trim().toLowerCase() === 'y'; } finally { rl.close(); }
}

export async function runSetup(options: SetupOptions = {}): Promise<SetupResult> {
  const rootDir = path.resolve(options.rootDir ?? process.cwd());
  const envFile = path.join(rootDir, '.env.local');
  const sqlitePath = path.join(rootDir, 'data', 'mohobot.db');
  const directoriesCreated: string[] = [];

  for (const relative of DIRECTORIES) {
    const full = path.join(rootDir, relative);
    const existed = await exists(full);
    await fs.mkdir(full, { recursive: true });
    if (!existed) directoriesCreated.push(relative);
  }

  let envCreated = false;
  let adminToken: string;
  if (await exists(envFile)) {
    const current = await fs.readFile(envFile, 'utf8');
    const match = current.match(/^MOHO_ADMIN_TOKEN=(.+)$/m);
    adminToken = match?.[1]?.trim() ?? '';
    if (!adminToken && options.force) {
      adminToken = token();
      await fs.appendFile(envFile, `\nMOHO_ADMIN_TOKEN=${adminToken}\n`, { encoding: 'utf8' });
    } else if (!adminToken) {
      if (options.nonInteractive) throw new Error('.env.local exists but has no MOHO_ADMIN_TOKEN; rerun with --force or add it manually');
      const accepted = await confirm('.env.local has no MOHO_ADMIN_TOKEN. Generate and append one?', options.input ?? input, options.output ?? output);
      if (!accepted) throw new Error('setup cancelled: administrator token is required');
      adminToken = token();
      await fs.appendFile(envFile, `\nMOHO_ADMIN_TOKEN=${adminToken}\n`, { encoding: 'utf8' });
    }
  } else {
    adminToken = token();
    await fs.writeFile(envFile, envContent(adminToken), { encoding: 'utf8', flag: 'wx', mode: 0o600 });
    envCreated = true;
  }

  // Machine-owned YAML lives only in ignored overlays, so upstream template
  // updates never conflict with production edits.
  const globalLocal=path.join(rootDir,'config','global.local.yaml');
  if(!await exists(globalLocal))await fs.writeFile(globalLocal,'# Machine-local overrides. This file is ignored by Git.\nversion: 1\n',{encoding:'utf8',flag:'wx',mode:0o600});
  const botLocal=path.join(rootDir,'config','bots','main.local.yaml');
  if(!await exists(botLocal))await fs.writeFile(botLocal,'# Machine-local overrides for bot main.\n',{encoding:'utf8',flag:'wx',mode:0o600});

  const storage = new SqliteStorage({ path: sqlitePath, logger: createNullLogger() });
  await storage.init();
  await storage.close();

  return { rootDir, envFile, envCreated, adminToken, directoriesCreated, sqlitePath, sqliteInitialized: true };
}

function hasFlag(args: string[], flag: string): boolean { return args.includes(flag); }

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const nonInteractive = hasFlag(process.argv.slice(2), '--non-interactive');
  const force = hasFlag(process.argv.slice(2), '--force');
  runSetup({ nonInteractive, force })
    .then((result) => {
      console.log(`MohoBot setup complete: ${result.rootDir}`);
      console.log(`.env.local: ${result.envCreated ? 'created' : 'kept existing'}`);
      console.log(`SQLite: ${result.sqlitePath}`);
      if (result.envCreated) console.log('MOHO_ADMIN_TOKEN generated and stored in .env.local (not printed).');
    })
    .catch((error: unknown) => { console.error(`MohoBot setup failed: ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; });
}
