import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import YAML from 'yaml';

export interface CommandResult { code: number; stdout: string; stderr: string }
export interface CommandRunner { run(command: string, args: readonly string[], options: { cwd: string }): Promise<CommandResult> }
export interface UpdateOptions { rootDir?: string; checkOnly?: boolean; allowAhead?: boolean; restartCommand?: readonly string[]; healthUrl?: string; healthTimeoutMs?: number }
export interface UpdateResult { mode: 'check'|'update'; initialHead: string; finalHead: string; branch: string; upstream: string; ahead: number; behind: number; backupPath?: string; restarted: boolean; healthy?: boolean }
export interface UpdateDependencies { runner?: CommandRunner; backup?: (databasePath: string, backupPath: string) => Promise<void>; healthCheck?: (url: string, timeoutMs: number) => Promise<void>; now?: () => Date; output?: Pick<Console,'log'|'error'>; nodeVersion?: string }
interface RecoveryPoint { rootDir: string; initialHead?: string; currentHead?: string; branch?: string; upstream?: string; backupPath?: string }

export class UpdateError extends Error { constructor(message: string) { super(message); this.name='UpdateError'; } }

const defaultRunner: CommandRunner={run(command,args,options){return new Promise((resolve,reject)=>{const child=spawn(command,[...args],{cwd:options.cwd,shell:false,stdio:['ignore','pipe','pipe'],env:process.env});const stdout:Buffer[]=[];const stderr:Buffer[]=[];child.stdout.on('data',(chunk:Buffer)=>stdout.push(chunk));child.stderr.on('data',(chunk:Buffer)=>stderr.push(chunk));child.once('error',reject);child.once('close',(code)=>resolve({code:code??1,stdout:Buffer.concat(stdout).toString('utf8').trim(),stderr:Buffer.concat(stderr).toString('utf8').trim()}));});}};

function requireNode22(version:string):void{const major=Number.parseInt(version.replace(/^v/,'').split('.')[0]??'',10);if(!Number.isInteger(major)||major<22)throw new UpdateError(`Node.js 22 or newer is required; found ${version}`);}
async function must(runner:CommandRunner,rootDir:string,command:string,args:readonly string[]):Promise<string>{const result=await runner.run(command,args,{cwd:rootDir});if(result.code!==0)throw new UpdateError(`${command} ${args.join(' ')} failed: ${result.stderr||`exit ${result.code}`}`);return result.stdout;}
async function assertClean(runner:CommandRunner,rootDir:string):Promise<void>{const unmerged=await runner.run('git',['diff','--name-only','--diff-filter=U'],{cwd:rootDir});if(unmerged.code!==0)throw new UpdateError(`cannot inspect unmerged files: ${unmerged.stderr}`);if(unmerged.stdout.trim())throw new UpdateError(`unmerged files must be resolved first:\n${unmerged.stdout.trim()}`);for(const args of [['diff','--quiet'],['diff','--cached','--quiet']]as const){const result=await runner.run('git',args,{cwd:rootDir});if(result.code===1)throw new UpdateError('tracked working tree or index changes must be committed or stashed first');if(result.code!==0)throw new UpdateError(`git ${args.join(' ')} failed: ${result.stderr}`);}}
async function graph(runner:CommandRunner,rootDir:string):Promise<{ahead:number;behind:number}>{const raw=await must(runner,rootDir,'git',['rev-list','--left-right','--count','HEAD...@{u}']);const[a,b]=raw.trim().split(/\s+/).map(Number);if(!Number.isSafeInteger(a)||!Number.isSafeInteger(b))throw new UpdateError(`unexpected git graph output: ${raw}`);return{ahead:a!,behind:b!};}
function validateGraph(state:{ahead:number;behind:number},allowAhead:boolean):void{if(state.ahead>0&&state.behind>0)throw new UpdateError('local and upstream histories have diverged; refusing automatic update');if(state.ahead>0&&!allowAhead)throw new UpdateError('local branch is ahead of upstream; rerun with --allow-ahead only after reviewing local commits');}

async function acquireLock(rootDir:string):Promise<()=>Promise<void>>{const lockDir=path.join(rootDir,'.mohobot-update.lock');try{await fs.mkdir(lockDir,{mode:0o700});}catch(error){if((error as NodeJS.ErrnoException).code==='EEXIST')throw new UpdateError(`update lock already exists: ${lockDir}\nVerify no updater is running, then remove this directory manually.`);throw error;}await fs.writeFile(path.join(lockDir,'owner.json'),JSON.stringify({pid:process.pid,startedAt:new Date().toISOString()},null,2),{mode:0o600});return async()=>{await fs.rm(lockDir,{recursive:true,force:true});};}
function parseEnvFile(raw:string):Record<string,string>{const values:Record<string,string>={};for(const line of raw.split(/\r?\n/)){const match=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);if(!match?.[1]||match[2]===undefined)continue;let value=match[2];if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);values[match[1]]=value;}return values;}
async function resolveDatabasePath(rootDir:string):Promise<string|undefined>{let envPath=process.env.MOHO_STORAGE_PATH?.trim();if(!envPath){try{envPath=parseEnvFile(await fs.readFile(path.join(rootDir,'.env.local'),'utf8')).MOHO_STORAGE_PATH?.trim();}catch{/* optional */}}let driver='sqlite';let configured='./data/mohobot.db';try{const config=YAML.parse(await fs.readFile(path.join(rootDir,'config','global.yaml'),'utf8'))as{storage?:{driver?:unknown;path?:unknown}}|null;if(typeof config?.storage?.driver==='string')driver=config.storage.driver;if(typeof config?.storage?.path==='string')configured=config.storage.path;}catch{/* defaults */}if(driver!=='sqlite')return undefined;const selected=envPath||configured;if(selected===':memory:')return undefined;return path.isAbsolute(selected)?selected:path.resolve(rootDir,selected);}

export async function backupSqlite(databasePath:string,backupPath:string):Promise<void>{await fs.mkdir(path.dirname(backupPath),{recursive:true,mode:0o700});const source=new Database(databasePath,{readonly:true,fileMustExist:true});try{await source.backup(backupPath);}finally{source.close();}const verification=new Database(backupPath,{readonly:true,fileMustExist:true});try{const row=verification.pragma('quick_check',{simple:true});if(row!=='ok')throw new UpdateError(`SQLite backup verification failed: ${String(row)}`);}finally{verification.close();}}
function backupName(now:Date,head:string):string{return`mohobot-${now.toISOString().replace(/[:.]/g,'-')}-${head.slice(0,12)}.db`;}
async function defaultHealthCheck(url:string,timeoutMs:number):Promise<void>{const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw new UpdateError('health URL must use http or https');const deadline=Date.now()+timeoutMs;let last='not attempted';while(Date.now()<deadline){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Math.min(5_000,Math.max(1,deadline-Date.now())));try{const response=await fetch(parsed,{signal:controller.signal,redirect:'error'});if(response.ok)return;last=`HTTP ${response.status}`;}catch(error){last=error instanceof Error?error.message:String(error);}finally{clearTimeout(timer);}await new Promise(resolve=>setTimeout(resolve,1_000));}throw new UpdateError(`health check timed out after ${timeoutMs}ms: ${last}`);}
function recoveryText(point:RecoveryPoint):string{return['Recovery point (no automatic reset or restore was performed):',`  repository: ${point.rootDir}`,point.branch?`  branch: ${point.branch}`:undefined,point.upstream?`  upstream: ${point.upstream}`:undefined,point.initialHead?`  pre-update HEAD: ${point.initialHead}`:undefined,point.currentHead?`  current HEAD: ${point.currentHead}`:undefined,point.backupPath?`  verified SQLite backup: ${point.backupPath}`:undefined,point.initialHead?`  inspect code changes: git diff ${point.initialHead}..HEAD`:undefined,'Review the failure before choosing any manual code or database recovery action.'].filter(Boolean).join('\n');}

export async function runUpdate(options:UpdateOptions={},dependencies:UpdateDependencies={}):Promise<UpdateResult>{const rootDir=path.resolve(options.rootDir??process.cwd());const runner=dependencies.runner??defaultRunner;const output=dependencies.output??console;const point:RecoveryPoint={rootDir};requireNode22(dependencies.nodeVersion??process.version);const release=await acquireLock(rootDir);try{if((await must(runner,rootDir,'git',['rev-parse','--is-inside-work-tree'])).trim()!=='true')throw new UpdateError('not inside a git work tree');await assertClean(runner,rootDir);point.branch=await must(runner,rootDir,'git',['symbolic-ref','--quiet','--short','HEAD']);point.upstream=await must(runner,rootDir,'git',['rev-parse','--abbrev-ref','--symbolic-full-name','@{u}']);point.initialHead=await must(runner,rootDir,'git',['rev-parse','HEAD']);let state=await graph(runner,rootDir);validateGraph(state,options.allowAhead===true);if(options.checkOnly){output.log(`Check complete: ${point.branch} vs ${point.upstream}; ahead ${state.ahead}, behind ${state.behind}. No fetch or changes performed.`);return{mode:'check',initialHead:point.initialHead,finalHead:point.initialHead,branch:point.branch,upstream:point.upstream,...state,restarted:false};}
const databasePath=await resolveDatabasePath(rootDir);if(databasePath){try{await fs.access(databasePath);point.backupPath=path.join(rootDir,'data','backups',backupName(dependencies.now?.()??new Date(),point.initialHead));await(dependencies.backup??backupSqlite)(databasePath,point.backupPath);output.log(`Verified SQLite backup: ${point.backupPath}`);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;output.log(`SQLite database does not exist yet; backup skipped: ${databasePath}`);}}
await must(runner,rootDir,'git',['fetch','--prune']);state=await graph(runner,rootDir);validateGraph(state,options.allowAhead===true);if(state.behind>0)await must(runner,rootDir,'git',['merge','--ff-only','--no-edit','@{u}']);point.currentHead=await must(runner,rootDir,'git',['rev-parse','HEAD']);for(const[command,args]of[['npm',['ci']],['npm',['run','setup','--','--non-interactive']],['npm',['run','typecheck']],['npm',['test']],['npm',['run','build']]]as const)await must(runner,rootDir,command,args);let restarted=false;if(options.restartCommand){const[command,...args]=options.restartCommand;if(!command)throw new UpdateError('restart command argv must not be empty');await must(runner,rootDir,command,args);restarted=true;}if(options.healthUrl)await(dependencies.healthCheck??defaultHealthCheck)(options.healthUrl,options.healthTimeoutMs??90_000);const finalHead=point.currentHead??point.initialHead;output.log(`Update complete: ${point.initialHead.slice(0,12)} -> ${finalHead.slice(0,12)}`);return{mode:'update',initialHead:point.initialHead,finalHead,branch:point.branch,upstream:point.upstream,...state,backupPath:point.backupPath,restarted,...(options.healthUrl?{healthy:true}:{})};}catch(error){try{point.currentHead=await must(runner,rootDir,'git',['rev-parse','HEAD']);}catch{/* best effort */}output.error(recoveryText(point));throw error instanceof UpdateError?error:new UpdateError(error instanceof Error?error.message:String(error));}finally{await release();}}

export function parseRestartCommand(value:string):string[]{let parsed:unknown;try{parsed=JSON.parse(value);}catch{throw new UpdateError('--restart-command must be a JSON argv array, for example ["systemctl","restart","mohobot"]');}if(!Array.isArray(parsed)||parsed.length===0||!parsed.every(item=>typeof item==='string'&&item.length>0&&!item.includes('\u0000')))throw new UpdateError('--restart-command must be a non-empty JSON array of non-empty strings');return parsed;}
export function parseArgs(args:readonly string[]):UpdateOptions{const options:UpdateOptions={};for(let i=0;i<args.length;i+=1){const arg=args[i]!;if(arg==='--check-only')options.checkOnly=true;else if(arg==='--allow-ahead')options.allowAhead=true;else if(arg==='--restart-command')options.restartCommand=parseRestartCommand(args[++i]??'');else if(arg.startsWith('--restart-command='))options.restartCommand=parseRestartCommand(arg.slice('--restart-command='.length));else if(arg==='--health-url')options.healthUrl=args[++i];else if(arg.startsWith('--health-url='))options.healthUrl=arg.slice('--health-url='.length);else if(arg==='--health-timeout-ms')options.healthTimeoutMs=Number.parseInt(args[++i]??'',10);else if(arg==='--help'){console.log('Usage: npm run update -- [--check-only] [--allow-ahead] [--restart-command=\'["systemctl","restart","mohobot"]\'] [--health-url=http://127.0.0.1:3210/api/status]');return{checkOnly:true};}else throw new UpdateError(`unknown option: ${arg}`);}if(options.healthTimeoutMs!==undefined&&(!Number.isSafeInteger(options.healthTimeoutMs)||options.healthTimeoutMs<1_000))throw new UpdateError('--health-timeout-ms must be at least 1000');return options;}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(fileURLToPath(import.meta.url))){runUpdate(parseArgs(process.argv.slice(2))).catch((error:unknown)=>{console.error(`MohoBot update failed: ${error instanceof Error?error.message:String(error)}`);process.exitCode=1;});}
