export type AdminRole='viewer'|'operator'|'admin'|'developer';
export type AdminPermission='status.read'|'metrics.read'|'models.read'|'admin.actions.read'|'audit.read'|'characters.read'|'characters.write'|'world.read'|'world.write'|'world.confirm'|'device.read'|'device.write'|'memory.metadata.read'|'memory.read'|'memory.write'|'memory.delete'|'behavior.dry-run'|'plugin.reload'|'config.publish'|'code.write'|'users.read'|'users.create'|'users.update'|'users.disable'|'users.role.assign'|'users.credentials.rotate'|'sessions.read'|'sessions.revoke'|'gateway.read'|'plugin.read'|'runtime.restart'|'sessions.chat.read'|'sessions.chat.delete'|'outbox.read'|'outbox.retry'|'tasks.read'|'tasks.control'|'logs.read'|'providers.read'|'providers.probe'|'knowledge.read'|'knowledge.write'|'knowledge.delete'|'debug.chat'|'extensions.read'|'tokens.read'|'tokens.create'|'tokens.revoke';
const READ:AdminPermission[]=['status.read','metrics.read','models.read','characters.read','world.read','device.read','memory.metadata.read','gateway.read','plugin.read','sessions.chat.read','outbox.read','tasks.read','logs.read','providers.read','knowledge.read','extensions.read','tokens.read'];
const OPERATOR:AdminPermission[]=[...READ,'memory.read','behavior.dry-run','characters.write','world.write','device.write','sessions.chat.delete','outbox.retry','providers.probe','knowledge.write','debug.chat','tasks.control','tokens.create','tokens.revoke'];
const ADMIN:AdminPermission[]=[...OPERATOR,'admin.actions.read','audit.read','memory.write','memory.delete','world.confirm','plugin.reload','runtime.restart','config.publish','users.read','users.create','users.update','users.disable','users.role.assign','users.credentials.rotate','sessions.read','sessions.revoke','knowledge.delete'];
const GRANTS:Record<AdminRole,ReadonlySet<AdminPermission>>={viewer:new Set(READ),operator:new Set(OPERATOR),admin:new Set(ADMIN),developer:new Set([...ADMIN,'code.write'])};
export interface AdminPrincipal{id:string;role:AdminRole;enabled:boolean;}
export function permissionsFor(role:AdminRole):AdminPermission[]{return[...GRANTS[role]];}
export function can(principal:AdminPrincipal|undefined,permission:AdminPermission):boolean{return Boolean(principal?.enabled&&GRANTS[principal.role].has(permission));}
export function requirePermission(principal:AdminPrincipal|undefined,permission:AdminPermission):void{if(!can(principal,permission))throw new Error('forbidden');}
