import fs from 'node:fs/promises';import os from'node:os';import path from'node:path';import{afterEach,describe,expect,it}from'vitest';import{WorldStore}from'./world.js';import{DeviceStore}from'./device.js';import{AffinityStore}from'./affinity.js';
const roots:string[]=[];async function root(){const value=await fs.mkdtemp(path.join(os.tmpdir(),'moho-stores-'));roots.push(value);return value;}afterEach(async()=>{await Promise.all(roots.splice(0).map(value=>fs.rm(value,{recursive:true,force:true})));});
describe('versioned admin stores compatibility',()=>{
 it('migrates legacy World and keeps API data-only',async()=>{const r=await root(),file=path.join(r,'data/world/state.json');await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify({weather:'rain',mood:{energy:.3}}));const state=await new WorldStore(r).get();expect(state.weather).toBe('rain');expect(state).not.toHaveProperty('format');expect(JSON.parse(await fs.readFile(file,'utf8'))).toMatchObject({format:'mohobot-json',version:1,data:{weather:'rain'}});});
 it('migrates legacy Device and keeps defaults',async()=>{const r=await root(),file=path.join(r,'data/world/device.json');await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify({battery:5,network:'weak'}));const state=await new DeviceStore(r).get();expect(state).toMatchObject({battery:5,network:'weak',screen:'on'});expect(state).not.toHaveProperty('revision');});
 it('migrates legacy Affinity arrays',async()=>{const r=await root(),file=path.join(r,'data/memory/affinity.json');await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify([{botId:'b',userId:'u',score:4,interactions:1,lastReason:'kind',updatedAt:'x',notes:[]}]));expect(await new AffinityStore(r).get('b','u')).toMatchObject({score:4});expect(JSON.parse(await fs.readFile(file,'utf8')).revision).toBe(1);});
 it('does not lose concurrent affinity adjustments across instances',async()=>{const r=await root(),a=new AffinityStore(r),b=new AffinityStore(r);await Promise.all(Array.from({length:20},(_,i)=>(i%2?a:b).adjust('bot','user',1,'helpful')));expect(await a.get('bot','user')).toMatchObject({score:20,interactions:20});});
 it('preserves corrupt World bytes instead of replacing defaults',async()=>{const r=await root(),file=path.join(r,'data/world/state.json'),raw='{bad';await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,raw);await expect(new WorldStore(r).get()).rejects.toBeInstanceOf(SyntaxError);expect(await fs.readFile(file,'utf8')).toBe(raw);});
});
