import { afterEach, describe, expect, it, vi } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import Database from 'better-sqlite3';
import { backupSqlite, parseRestartCommand, runUpdate, type CommandRunner } from '../scripts/update.js';

const roots:string[]=[];
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>fs.rm(root,{recursive:true,force:true})));});
function command(command:string,args:string[],cwd:string):Promise<void>{return new Promise((resolve,reject)=>{const child=spawn(command,args,{cwd,stdio:'pipe',shell:false});let stderr='';child.stderr.on('data',chunk=>stderr+=String(chunk));child.once('error',reject);child.once('close',code=>code===0?resolve():reject(new Error(`${command} failed: ${stderr}`)));});}
async function tempGit():Promise<string>{const base=await fs.mkdtemp(path.join(os.tmpdir(),'mohobot-update-'));roots.push(base);const bare=path.join(base,'remote.git');const seed=path.join(base,'seed');const clone=path.join(base,'clone');await command('git',['init','--bare',bare],base);await fs.mkdir(seed);await command('git',['init','-b','main'],seed);await command('git',['config','user.email','test@example.invalid'],seed);await command('git',['config','user.name','Test'],seed);await fs.writeFile(path.join(seed,'tracked.txt'),'one\n');await command('git',['add','.'],seed);await command('git',['commit','-m','initial'],seed);await command('git',['remote','add','origin',bare],seed);await command('git',['push','-u','origin','main'],seed);await command('git',['symbolic-ref','HEAD','refs/heads/main'],bare);await command('git',['clone',bare,clone],base);return clone;}

describe('production updater',()=>{
  it('check-only inspects a temporary repository without fetch or mutation',async()=>{const root=await tempGit();const before=await fs.readFile(path.join(root,'tracked.txt'),'utf8');const result=await runUpdate({rootDir:root,checkOnly:true},{nodeVersion:'v22.0.0',output:{log:vi.fn(),error:vi.fn()}});expect(result).toMatchObject({mode:'check',branch:'main',upstream:'origin/main',ahead:0,behind:0,restarted:false});expect(await fs.readFile(path.join(root,'tracked.txt'),'utf8')).toBe(before);await expect(fs.access(path.join(root,'.mohobot-update.lock'))).rejects.toThrow();});
  it('check-only rejects tracked changes but permits untracked runtime files',async()=>{const root=await tempGit();await fs.writeFile(path.join(root,'runtime.tmp'),'ok');await expect(runUpdate({rootDir:root,checkOnly:true},{nodeVersion:'v22',output:{log:vi.fn(),error:vi.fn()}})).resolves.toBeTruthy();await fs.writeFile(path.join(root,'tracked.txt'),'dirty');await expect(runUpdate({rootDir:root,checkOnly:true},{nodeVersion:'v22',output:{log:vi.fn(),error:vi.fn()}})).rejects.toThrow('tracked working tree');});
  it('requires an explicit allow-ahead decision',async()=>{const root=await tempGit();await command('git',['config','user.email','test@example.invalid'],root);await command('git',['config','user.name','Test'],root);await fs.writeFile(path.join(root,'tracked.txt'),'local\n');await command('git',['add','.'],root);await command('git',['commit','-m','local'],root);await expect(runUpdate({rootDir:root,checkOnly:true},{nodeVersion:'v22',output:{log:vi.fn(),error:vi.fn()}})).rejects.toThrow('--allow-ahead');const result=await runUpdate({rootDir:root,checkOnly:true,allowAhead:true},{nodeVersion:'v22',output:{log:vi.fn(),error:vi.fn()}});expect(result.ahead).toBe(1);});
  it('never invokes fetch in check-only with an injected runner',async()=>{const calls:string[]=[];const runner:CommandRunner={async run(command,args){calls.push([command,...args].join(' '));const key=args.join(' ');if(key==='rev-parse --is-inside-work-tree')return{code:0,stdout:'true',stderr:''};if(key==='diff --name-only --diff-filter=U'||key==='diff --quiet'||key==='diff --cached --quiet')return{code:0,stdout:'',stderr:''};if(key==='symbolic-ref --quiet --short HEAD')return{code:0,stdout:'main',stderr:''};if(key==='rev-parse --abbrev-ref --symbolic-full-name @{u}')return{code:0,stdout:'origin/main',stderr:''};if(key==='rev-parse HEAD')return{code:0,stdout:'abc123',stderr:''};if(key==='rev-list --left-right --count HEAD...@{u}')return{code:0,stdout:'0 0',stderr:''};return{code:99,stdout:'',stderr:'unexpected'};}};const root=await fs.mkdtemp(path.join(os.tmpdir(),'mohobot-runner-'));roots.push(root);await runUpdate({rootDir:root,checkOnly:true},{runner,nodeVersion:'v22',output:{log:vi.fn(),error:vi.fn()}});expect(calls.some(call=>call.includes('fetch'))).toBe(false);});
  it('prints recovery data and never resets after a post-fetch failure',async()=>{const calls:string[]=[];const errors:string[]=[];let head='before';const runner:CommandRunner={async run(command,args){const key=[command,...args].join(' ');calls.push(key);if(key==='git rev-parse --is-inside-work-tree')return{code:0,stdout:'true',stderr:''};if(key==='git diff --name-only --diff-filter=U'||key==='git diff --quiet'||key==='git diff --cached --quiet')return{code:0,stdout:'',stderr:''};if(key==='git symbolic-ref --quiet --short HEAD')return{code:0,stdout:'main',stderr:''};if(key==='git rev-parse --abbrev-ref --symbolic-full-name @{u}')return{code:0,stdout:'origin/main',stderr:''};if(key==='git rev-list --left-right --count HEAD...@{u}')return{code:0,stdout:head==='before'?'0 1':'0 0',stderr:''};if(key==='git fetch --prune')return{code:0,stdout:'',stderr:''};if(key==='git merge --ff-only --no-edit @{u}'){head='after';return{code:0,stdout:'',stderr:''};}if(key==='git rev-parse HEAD')return{code:0,stdout:head,stderr:''};if(key==='npm ci')return{code:1,stdout:'',stderr:'install failed'};return{code:99,stdout:'',stderr:'unexpected'};}};const root=await fs.mkdtemp(path.join(os.tmpdir(),'mohobot-failure-'));roots.push(root);await expect(runUpdate({rootDir:root},{runner,nodeVersion:'v22',output:{log:vi.fn(),error:(message?:unknown)=>{errors.push(String(message));}}})).rejects.toThrow('install failed');expect(calls.some(call=>/reset|checkout/.test(call))).toBe(false);expect(errors.join('\n')).toContain('pre-update HEAD: before');expect(errors.join('\n')).toContain('current HEAD: after');});
  it('uses SQLite backup API and verifies a readable copy',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'mohobot-db-'));roots.push(root);const source=path.join(root,'source.db');const backup=path.join(root,'backups','copy.db');const db=new Database(source);db.exec('CREATE TABLE sample(value TEXT); INSERT INTO sample VALUES (\'safe\')');db.close();await backupSqlite(source,backup);const copy=new Database(backup,{readonly:true});expect((copy.prepare('SELECT value FROM sample').get()as{value:string}).value).toBe('safe');copy.close();});
  it('restart command is JSON argv rather than shell text',()=>{expect(parseRestartCommand('["systemctl","restart","mohobot"]')).toEqual(['systemctl','restart','mohobot']);expect(()=>parseRestartCommand('systemctl restart mohobot')).toThrow('JSON argv');expect(()=>parseRestartCommand('[]')).toThrow('non-empty');});
});
