import{createHash,randomUUID}from'node:crypto';import type{Storage}from'../storage/types.js';
const P='knowledge:';const V=1;const MAX_NAME=120,MAX_DOC=512*1024,MAX_CHUNKS=512,CHUNK=1200,OVERLAP=160;
type Kind='knowledge-base'|'knowledge-document'|'knowledge-chunk'|'knowledge-binding';interface Envelope{kind:Kind;recordVersion:number;updatedAt:number;}
export interface KnowledgeBase extends Envelope{id:string;name:string;description:string;createdAt:number;documentCount:number}
export interface KnowledgeDocument extends Envelope{id:string;baseId:string;name:string;text:string;textHash:string;createdAt:number;chunkCount:number}
interface KnowledgeChunk extends Envelope{id:string;baseId:string;documentId:string;index:number;text:string;textHash:string}
export interface KnowledgeBinding extends Envelope{baseId:string;targetType:'bot'|'character';targetId:string;createdAt:number}
export interface KnowledgePage<T>{items:T[];offset:number;limit:number;total:number}
function key(k:string){return`${P}${k}`};function validId(x:unknown){return typeof x==='string'&&/^[a-zA-Z0-9_-]{1,96}$/.test(x)}function assertId(x:string,n='id'){if(!validId(x))throw Error(`invalid ${n}`)}function hash(x:string){return createHash('sha256').update(x).digest('hex')}function norm(x:string){return x.replace(/\r\n?/g,'\n').replace(/[ \t]+\n/g,'\n').trim()}
function env<T extends Envelope>(x:unknown,kind:Kind):T|undefined{if(!x||typeof x!=='object'||Array.isArray(x))return;const v=x as Partial<Envelope>;if(v.kind!==kind||!Number.isSafeInteger(v.recordVersion)||v.recordVersion!==V)return;return x as T}
function page<T>(items:T[],offset=0,limit=50):KnowledgePage<T>{if(!Number.isSafeInteger(offset)||offset<0||!Number.isSafeInteger(limit)||limit<1||limit>200)throw Error('invalid pagination');return{items:items.slice(offset,offset+limit),offset,limit,total:items.length}}
function chunks(text:string){const out:string[]=[];for(let at=0;at<text.length;){let end=Math.min(text.length,at+CHUNK);if(end<text.length){const split=Math.max(text.lastIndexOf('\n',end),text.lastIndexOf(' ',end));if(split>at+Math.floor(CHUNK*.55))end=split;}out.push(text.slice(at,end).trim());if(end>=text.length)break;at=Math.max(end-OVERLAP,at+1);}return out.filter(Boolean)}
export class KnowledgeBaseStore{constructor(private readonly storage:Storage){}
 async create(input:{id?:string;name:string;description?:string}){const id=input.id??randomUUID();assertId(id,'base id');const name=norm(input.name);if(!name||name.length>MAX_NAME)throw Error('invalid knowledge base name');if(await this.storage.get(key(`base:${id}`)))throw Error('knowledge base exists');const now=Date.now(),row:KnowledgeBase={kind:'knowledge-base',recordVersion:V,id,name,description:norm(input.description??'').slice(0,2000),createdAt:now,updatedAt:now,documentCount:0};await this.storage.save(key(`base:${id}`),row);return row}
 async list(offset=0,limit=50){const rows=await this.storage.query<unknown>({prefix:key('base:'),limit:1000});return page(rows.map(r=>env<KnowledgeBase>(r.value,'knowledge-base')).filter((x):x is KnowledgeBase=>Boolean(x)).sort((a,b)=>b.updatedAt-a.updatedAt),offset,limit)}
 async get(id:string){assertId(id,'base id');return env<KnowledgeBase>(await this.storage.get(key(`base:${id}`)),'knowledge-base')}
 async delete(id:string){assertId(id,'base id');if(!await this.get(id))return false;for(const prefix of [`document:${id}:`,`chunk:${id}:`,`binding:${id}:`])for(const row of await this.storage.query({prefix:key(prefix),limit:10000}))await this.storage.delete(row.key);await this.storage.delete(key(`base:${id}`));return true}
 async upsertDocument(input:{baseId:string;id?:string;name:string;text:string}){assertId(input.baseId,'base id');const base=await this.get(input.baseId);if(!base)throw Error('knowledge base not found');const text=norm(input.text);if(!text||Buffer.byteLength(text,'utf8')>MAX_DOC)throw Error('document too large or empty');const name=norm(input.name);if(!name||name.length>MAX_NAME)throw Error('invalid document name');const id=input.id??hash(`${input.baseId}\0${name}`).slice(0,32);assertId(id,'document id');const split=chunks(text);if(split.length>MAX_CHUNKS)throw Error('too many chunks');const now=Date.now(),old=env<KnowledgeDocument>(await this.storage.get(key(`document:${input.baseId}:${id}`)),'knowledge-document');if(old)for(const row of await this.storage.query({prefix:key(`chunk:${input.baseId}:${id}:`),limit:MAX_CHUNKS+1}))await this.storage.delete(row.key);const doc:KnowledgeDocument={kind:'knowledge-document',recordVersion:V,id,baseId:input.baseId,name,text,textHash:hash(text),createdAt:old?.createdAt??now,updatedAt:now,chunkCount:split.length};await this.storage.save(key(`document:${input.baseId}:${id}`),doc);for(let i=0;i<split.length;i++){const c:KnowledgeChunk={kind:'knowledge-chunk',recordVersion:V,id:hash(`${doc.textHash}:${i}`).slice(0,32),baseId:input.baseId,documentId:id,index:i,text:split[i]!,textHash:hash(split[i]!),updatedAt:now};await this.storage.save(key(`chunk:${input.baseId}:${id}:${String(i).padStart(4,'0')}`),c)}base.documentCount+=old?0:1;base.updatedAt=now;await this.storage.save(key(`base:${input.baseId}`),base);return{...doc,text:undefined} as Omit<KnowledgeDocument,'text'>}
 async listDocuments(baseId:string,offset=0,limit=50){assertId(baseId,'base id');const rows=await this.storage.query<unknown>({prefix:key(`document:${baseId}:`),limit:2000});const docs=rows.map(r=>env<KnowledgeDocument>(r.value,'knowledge-document')).filter((x):x is KnowledgeDocument=>Boolean(x)).sort((a,b)=>b.updatedAt-a.updatedAt).map(({text,...d})=>({...d,textLength:Buffer.byteLength(text,'utf8')}));return page(docs,offset,limit)}
 async getDocument(baseId:string,id:string){assertId(baseId,'base id');assertId(id,'document id');return env<KnowledgeDocument>(await this.storage.get(key(`document:${baseId}:${id}`)),'knowledge-document')}
 async deleteDocument(baseId:string,id:string){const doc=await this.getDocument(baseId,id);if(!doc)return false;for(const row of await this.storage.query({prefix:key(`chunk:${baseId}:${id}:`),limit:MAX_CHUNKS+1}))await this.storage.delete(row.key);await this.storage.delete(key(`document:${baseId}:${id}`));const base=await this.get(baseId);if(base){base.documentCount=Math.max(0,base.documentCount-1);base.updatedAt=Date.now();await this.storage.save(key(`base:${baseId}`),base)}return true}
 async search(input:{baseId:string;query:string;offset?:number;limit?:number}){assertId(input.baseId,'base id');const terms=[...new Set(norm(input.query).toLowerCase().split(/\s+/).filter(x=>x.length>1).slice(0,12))];if(!terms.length)return page([],input.offset,input.limit);const rows=await this.storage.query<unknown>({prefix:key(`chunk:${input.baseId}:`),limit:MAX_CHUNKS*200});const result=rows.map(r=>env<KnowledgeChunk>(r.value,'knowledge-chunk')).filter((x):x is KnowledgeChunk=>Boolean(x)).map(c=>({documentId:c.documentId,chunkId:c.id,index:c.index,text:c.text,score:terms.reduce((n,t)=>n+(c.text.toLowerCase().split(t).length-1),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.documentId.localeCompare(b.documentId)||a.index-b.index);return page(result,input.offset,input.limit)}
 async bind(input:{baseId:string;targetType:'bot'|'character';targetId:string}){assertId(input.baseId,'base id');assertId(input.targetId,'target id');if(!['bot','character'].includes(input.targetType))throw Error('invalid binding target');if(!await this.get(input.baseId))throw Error('knowledge base not found');const now=Date.now(),row:KnowledgeBinding={kind:'knowledge-binding',recordVersion:V,baseId:input.baseId,targetType:input.targetType,targetId:input.targetId,createdAt:now,updatedAt:now};await this.storage.save(key(`binding:${input.baseId}:${input.targetType}:${input.targetId}`),row);return row}
 async bindings(baseId:string){assertId(baseId,'base id');const rows=await this.storage.query<unknown>({prefix:key(`binding:${baseId}:`),limit:1000});return rows.map(r=>env<KnowledgeBinding>(r.value,'knowledge-binding')).filter((x):x is KnowledgeBinding=>Boolean(x))}
 async unbind(baseId:string,targetType:'bot'|'character',targetId:string){assertId(baseId,'base id');assertId(targetId,'target id');const k=key(`binding:${baseId}:${targetType}:${targetId}`);if(!env<KnowledgeBinding>(await this.storage.get(k),'knowledge-binding'))return false;await this.storage.delete(k);return true}
}
