import { describe,expect,it,vi } from 'vitest';
import type { ResolvedMediaProviderConfig } from '../config/schema.js';
import { OpenAICompatibleOcrProvider,OpenAICompatibleVisionProvider } from './openai-compatible.js';
const cfg=(overrides:Partial<ResolvedMediaProviderConfig>={}):ResolvedMediaProviderConfig=>({enabled:true,baseUrl:'https://vision.example/v1',model:'vision-model',apiKeyEnv:'VISION_KEY',apiKey:'secret',timeoutMs:1000,...overrides});
describe('OpenAI-compatible media providers',()=>{
 it('sends a base64 data URL and strictly reads text content',async()=>{let body:any;const fetchImpl=vi.fn(async(_url:unknown,init?:RequestInit)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify({choices:[{message:{content:' visible scene '}}]}),{status:200,headers:{'content-type':'application/json'}});}) as unknown as typeof fetch;const provider=new OpenAICompatibleVisionProvider(cfg(),{fetchImpl});await expect(provider.describe({bytes:new Uint8Array([1,2]),mime:'image/png',prompt:'describe'})).resolves.toBe('visible scene');expect(body.messages[0].content[1].image_url.url).toBe('data:image/png;base64,AQI=');expect(body.model).toBe('vision-model');});
 it('uses an OCR-only untrusted-data prompt',async()=>{let prompt='';const fetchImpl=vi.fn(async(_url:unknown,init?:RequestInit)=>{prompt=JSON.parse(String(init?.body)).messages[0].content[0].text;return new Response(JSON.stringify({choices:[{message:{content:'hello'}}]}),{status:200});}) as unknown as typeof fetch;await new OpenAICompatibleOcrProvider(cfg(),{fetchImpl}).recognize({bytes:new Uint8Array([1]),mime:'image/jpeg'});expect(prompt).toContain('untrusted');expect(prompt).toContain('Return text only');});
 it.each([{}, {choices:[]},{choices:[{}]},{choices:[{message:{content:7}}]}])('rejects malformed responses %#',async(payload)=>{const fetchImpl=vi.fn(async()=>new Response(JSON.stringify(payload),{status:200})) as unknown as typeof fetch;await expect(new OpenAICompatibleVisionProvider(cfg(),{fetchImpl}).describe({bytes:new Uint8Array([1]),mime:'image/png',prompt:'x'})).rejects.toThrow(/response/);});
 it('enforces timeout and rejects non-image MIME',async()=>{const fetchImpl=vi.fn(async(_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(Object.assign(new Error('abort'),{name:'AbortError'})),{once:true}))) as unknown as typeof fetch;const provider=new OpenAICompatibleVisionProvider(cfg({timeoutMs:5}),{fetchImpl});await expect(provider.describe({bytes:new Uint8Array([1]),mime:'image/png',prompt:'x'})).rejects.toThrow('timed out');await expect(provider.describe({bytes:new Uint8Array([1]),mime:'text/plain',prompt:'x'})).rejects.toThrow('image MIME');});
});
